# Generated by Django 5.2.6 on 2025-09-24 11:24

import books.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='دسته بندی')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت نمایش')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('desc', models.TextField(verbose_name='توضیحات کوتاه')),
                ('author', models.CharField(max_length=150, verbose_name='نویسنده')),
                ('content', models.TextField(verbose_name='توضیحات کامل')),
                ('cover_image', models.ImageField(upload_to=books.utils.image_upload_book, verbose_name='کاور کتاب')),
                ('is_published', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروز شده در')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر اضافه کننده')),
                ('categories', models.ManyToManyField(related_name='books', to='books.bookcategory', verbose_name='دسته بندی')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
