# Generated by Django 5.2.6 on 2025-09-26 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_borrow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['-borrowed_at'], 'verbose_name': 'امانت', 'verbose_name_plural': 'امانت\u200cها'},
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='books.book', verbose_name='کتاب'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrowed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ امانت'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='تحویل داده شده؟'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
