# Generated by Django 5.2.6 on 2025-09-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_borrow_options_alter_borrow_book_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['-borrowed_at']},
        ),
    ]
