# Generated by Django 5.2.6 on 2025-09-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_borrow_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_borrowed',
            field=models.BooleanField(default=False, verbose_name='در امانت؟'),
        ),
    ]
