# Generated by Django 5.2.6 on 2025-09-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_is_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
    ]
