# Generated by Django 5.2.6 on 2025-09-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_borrow_returned_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='returned_at',
        ),
    ]
